version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    restart: always

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /shared/docker/volumes/bot_onet/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    env_file:
      - ../.env
