name: Deployment

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Setup bot
      run: |
        rm -r /var/www/bot/discord
        mkdir /var/www/bot/discord
        cd /var/www/bot/discord
        git clone https://github.com/C0casio45/bot_onet.git /var/www/bot/discord
    - name: create json file
      run: |
        touch config.json
        echo {"token":"${{ config.DISCORDTOKEN }}","folder":"${{ config.FOLDER }}","logs":"${{ config.LOGS }}","faceit":{"token":"${{ config.FACEITTOKEN }}","guid":"${{ config.GUID }}","hubId":"${{ config.HUBID }}","clientAPIKey":"${{ config.CLIENTAPIKEY }}"}}
    - name: run bot
      run: |
        pm2 stop bot
        pm2 start bot