name: Deployment

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Setup bot
      run: |
        cd /var/www/bot/discord
        rm -r /var/www/bot/discord/
        git clone https://github.com/C0casio45/bot_onet.git /var/www/bot/discord
        pm2 stop bot
        pm2 start bot