name: Deployment

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16]
    
    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: node-version ${{ matrix.node-version }}
    - run: npm i