name: Deployment

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Setup bot
      run: |
        rm -r /var/www/bot/discord
        mkdir /var/www/bot/discord
        cd /var/www/bot/discord
        git clone https://github.com/C0casio45/bot_onet.git /var/www/bot/discord
        npm i
    - name: create json file
      env:
        DISCORDTOKEN: ${{ env.DISCORDTOKEN }}
        FOLDER: ${{ env.FOLDER }}
        LOGS: ${{ env.LOGS }}
        GUID: ${{ env.GUID }}
        HUBID: ${{ env.HUBID }}
        CLIENTAPIKEY: ${{ env.CLIENTAPIKEY }}
      run: echo "{\"token\":\"$DISCORDTOKEN\",\"folder\":\"$FOLDER\",\"logs\":\"$LOGS\",\"faceit\":{\"token\":\"$FACEITTOKEN\",\"guid\":\"$GUID\",\"hubId\":\"$HUBID\",\"clientAPIKey\":\"$CLIENTAPIKEY\"}}" > /var/www/bot/discord/config.json
    - name: run bot
      run: |
        pm2 stop bot
        pm2 start bot