name: Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - uses: 8BitJonny/gh-get-current-pr@2.1.1
      id: PR


#     - name: "Deploying [MAJOR] release"
#       if: "contains(steps.PR.outputs.pr_title, '[MAJOR]')"
#       run: 1.0.0 to 2.0.0
#     - name: "Deploying [MINOR] release"
#       if: "contains(steps.PR.outputs.pr_title, '[MINOR]')"
#       run: 1.0.0 to 1.1.0
#     - name: "Deploying [PATCH] release"
#       if: "contains(steps.PR.outputs.pr_title, '[PATCH]')"
#       run: 1.0.0 to 1.0.1
#     - name: "Deploying [OTHER] release"
#       if: "contains(steps.PR.outputs.pr_title, '[OTHER]')"
#       run: 1.0.0 to 1.0.1
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Setup bot
      run: |
        rm -r /var/www/bot/discord
        mkdir /var/www/bot/discord
        cd /var/www/bot/discord
        git clone https://github.com/C0casio45/bot_onet.git /var/www/bot/discord
        npm i
    - name: Create json file
      env:
        DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
        FOLDER: ${{ secrets.FOLDER }}
        LOGS: ${{ secrets.LOGS }}
        GUID: ${{ secrets.GUID }}
        HUBID: ${{ secrets.HUBID }}
        CLIENTAPIKEY: ${{ secrets.CLIENTAPIKEY }}
        FACEITTOKEN: ${{ secrets.FACEITTOKEN }}
      run: echo "{\"token\":\"$DISCORDTOKEN\",\"folder\":\"$FOLDER\",\"logs\":\"$LOGS\",\"faceit\":{\"token\":\"$FACEITTOKEN\",\"guid\":\"$GUID\",\"hubId\":\"$HUBID\",\"clientAPIKey\":\"$CLIENTAPIKEY\"}}" > /var/www/bot/discord/config.json
    - name: Create DBConnect.js
      env:
        DBCONNECT: ${{ secrets.DBCONNECT }}
      run: echo "$DBCONNECT" > /var/www/bot/discord/utils/dbconnect.js
    - run: echo -e "title ${{ steps.PR.outputs.pr_title  }} \ndesc ${{ steps.PR.outputs.pr_body }}" > /home/pi/.pm2/logs/bot-error.log
    - name: run bot
      run: |
        pm2 stop bot
        pm2 start bot
